---
image: jembi/platform
defaultTargetLauncher: swarm
disableKubernetes: true
disableIG: true
disableCustomTargetSelection: true
logPath: /tmp/logs
packages:
  - id: interoperability-layer-openhim
    name: Interoperability Layer - OpenHIM
  - id: reverse-proxy-nginx
    name: Reverse Proxy - NGINX
  - id: fhir-datastore-hapi-fhir
    name: FHIR Data Store - HAPI-FHIR
  - id: message-bus-kafka
    name: Message Bus - Kafka
  - id: analytics-datastore-elastic-search
    name: Analytics Datastore - ElasticSearch
  - id: dashboard-visualiser-kibana
    name: Dashboard Visualiser - Kibana
  - id: data-mapper-logstash
    name: Data Mapper - Logstash
  - id: dashboard-visualiser-jsreport
    name: Dashboard Visualiser - JS Reports
  - id: client-registry-santempi
    name: Client Registry - SanteMPI
  - id: fhir-datastore-helper-hapi-fhir
    name: FHIR IG importer
  - id: message-bus-helper-hapi-proxy
    name: Message Bus Helper - HAPI Proxy to Kafka
  - id: job-scheduler-ofelia
    name: Job Scheduler Ofelia
  - id: kafka-mapper-consumer
    name: Kafka Mapper Consumer
  - id: kafka-unbundler-consumer
    name: Kafka Unbundler Consumer
  - id: analytics-datastore-clickhouse
    name: Analytics Datastore Clickhouse
  - id: dashboard-visualiser-superset
    name: Dashboard Visualiser Superset
  - id: monitoring
    name: Monitoring package
